version: "3"
services:
  app:
    container_name: bot
    build:
      context: "./"
      dockerfile: "Dockerfile"
    volumes:
      - "./:/var/bot/"
    tty: true
    restart: always
    command: python bot.py
